language: php

services:
  - docker

sudo: required

# Replace with your image name.
before_script:
  - docker pull bcondon/docker_tripal3

script:
  - git clone https://github.com/statonlab/tripal_alchemist.git
  - docker run -d -v tripal_alchemist:/var/www/html/sites/all/modules/tripal_extensions/tripal_alchemist  --name tripal -p 8080:80 bcondon/docker_tripal3
  - docker exec -it tripal echo "hello!"
    - docker exec -it tripal drush pm-enable -y tripal_alchemist
  - docker exec -it tripal cd /var/www/html/sites/all/modules/tripal_extensions/tripal_alchemist/test && phpunit
